package com.queryLayer;

import java.util.*;

import com.queryLayer.databaseSchemaEnums.Column;
import com.queryLayer.databaseSchemaEnums.Table;

public class Query {
	private StringBuilder queryString;
	private QueryType queryType;
	private List<Object> values;
	private List<Column> columns;
	private List<Object> queryParams;
	private List<Table> tables;
	private List<Condition> conditions;
	private int autoGeneratedKey;

	public Query() {
		values = new ArrayList<>();
		tables = new ArrayList<>();
		queryParams = new ArrayList<>();
		queryString = new StringBuilder();
	}

	public List<Object> getValues() {
		return values;
	}

	public void setValues(List<Object> values) {
		this.values = values;
	}

	public List<Column> getColumns() {
		return columns;
	}

	public void setColumns(List<Column> columns) {
		this.columns = columns;
	}

	public List<Table> getTables() {
		return tables;
	}

	public void setTables(List<Table> tables) {
		this.tables = tables;
	}

	public void setQueryString(StringBuilder queryString) {
		this.queryString = queryString;
	}

	public StringBuilder getQueryString() {
		return queryString;
	}
	
	public void appendQueryString(String queryString) {
		this.queryString.append(queryString);
	}

	public void setQueryType(QueryType queryType) {
		this.queryType = queryType;
	}

	public QueryType getQueryType() {
		return this.queryType;
	}

	public void addParameter(Object param) {
		this.values.add(param);
	}

	public List<Object> getParameters() {
		return values;
	}

	public Object[] getParametersArray() {
		return values.toArray();
	}

	public void addTable(Table table) {
		if (this.tables == null)
			this.tables = new ArrayList<>();
		this.tables.add(table);
	}

	public void addColumn(Column col) {
		if (this.columns == null)
			this.columns = new ArrayList<>();
		this.columns.add(col);
	}

	public void addValue(Object val) {
		if (this.values == null)
			this.values = new ArrayList<>();
		this.values.add(val);
	}
	public void addQueryParams(Object val) {
		this.queryParams.add(val);
	}
	public List<Object> getQueryParams(){
		return queryParams;
	}
	public int getAutoGeneratedKey() {
		return this.autoGeneratedKey;
	}

	public void setAutoGeneratedKey(int autoGeneratedKey) {
		this.autoGeneratedKey = autoGeneratedKey;
	}

	public void addCondition(Column col, String condition, Object value) {
		if (this.conditions == null)
			this.conditions = new ArrayList<>();
		this.conditions.add(new Condition(col, value, condition));
	}

	public List<Condition> getConditions() {
		return this.conditions;
	}
}